spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/bitchron?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: ${USERNAME}
        password: ${ADMIN_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        properties:
            hibernate:
                format_sql: true
        hibernate:
            ddl-auto: update
    sql:
        init:
            mode: always
logging:
    level:
        org.hibernate.SQL: DEBUG
        org.hibernate.orm.jdbc.bind: TRACE
        org.springframework.security: TRACE
bitcron:
    remember.me.key: ${REMEMBER_ME_KEY}